Update enemy.py
TriCot-Game-Studio/bullets pull request #19
Opened 2020-10-12 21:43 UTC by deceptikhanqueror

i couldn't really understand how you are doing patterns, so i wasn't able to implement those in the class, but if you are willing to explain how you are doing patterns, I could implement that as well - also wasn't sure how to implement damage dealt, so i created a variable that you can update with the interactions with player (again, if you explained how your system works, i could probably do that as well)

I based the phase change system on health thresholds, assuming 4 phases (this can easily be changed to suit your needs)

let me know if you have any questions, and if this project is still being worked on

2020-10-12 21:55 UTC, AdamSpannbauer commented
Hey @deceptikhanqueror thanks for the PR, I like the idea of the `pcb` (and i also like the name). Give me a sec to pull it down and play with it.

And totally fair feedback on the bullet pattern.  We started this project in a very game-jam, just get it going way and the code/direction could be clearer.  I'll try and do some clean up to make this more approachable.

2020-10-12 22:07 UTC, deceptikhanqueror commented
cool thanks @AdamSpannbauer , yeah it seems like a very interesting project
hmu if you need anything else, I would be happy to help 

Discord: Khanqueror #7148

2020-10-12 22:50 UTC, AdamSpannbauer requested changes
Hey @deceptikhanqueror, again, thanks for the PR.  I made some comments on the code.  A lot of what I commented on would be caught by some static code analysis.  This could be done by an IDE (I often use pycharm), or maybe a text editor plugin (i know vscode has pretty good python plugin).  While I'm recommending tools, we've also been using [`black`](https://pypi.org/project/black/) in the project so far to auto-format all of the code.  If you'd prefer not to install, then expect for my to make a formatting commit before merging your PR.

Let me know if you want any help refactoring the code.

2020-10-12 22:50 UTC, AdamSpannbauer commented on bullets/enemy.py
> +    def __init__(maxhealth, patterns, pcb1, pcb2, pcb3 )
* the first parameter of a method that uses `self` should be `self`
* `def` lines should end with a `:`

2020-10-12 22:50 UTC, AdamSpannbauer commented on bullets/enemy.py
> +        self.status = "Alive"
i think i like this being `self.is_alive = True` or potentially using a property/getter like [here in player.py](https://github.com/TriCot-Game-Studio/bullets/blob/main/bullets/player.py#L16-L18).

2020-10-12 22:50 UTC, AdamSpannbauer commented on bullets/enemy.py
> +    def update(damage)
see comments on the `__init__` method about `self` & `:`

2020-10-12 22:50 UTC, AdamSpannbauer commented on bullets/enemy.py
> +            self.phase = 3
`maxhealth` and the `pcb{n}`s need some `self.`s

2020-10-12 23:56 UTC, deceptikhanqueror commented
@AdamSpannbauer made the changes that you requested in new commit 
let me know if I did something wrong

2020-10-13 00:37 UTC, AdamSpannbauer requested changes
I think this is the last bit before we'll get this merged this in.

2020-10-13 00:37 UTC, AdamSpannbauer commented on bullets/enemy.py
> +    def __init__(self, maxhealth, pcb1, pcb2, pcb3):
To inherit all the `Actor` stuff (which admittedly isn't much rn), we need to call the `super()`'s `__init__` method.  You can see this [here in `Player`](https://github.com/TriCot-Game-Studio/bullets/blob/main/bullets/player.py#L5-L6).

2020-10-13 00:37 UTC, AdamSpannbauer commented on bullets/enemy.py
> +    def __init__(self, maxhealth, pcb1, pcb2, pcb3):
This would also require for `Enemy`'s `__init__()` to get a few more params.

2020-10-13 01:04 UTC, deceptikhanqueror commented
OK, I think I did what you wanted, can you confirm that is what you wanted? @AdamSpannbauer

2020-10-13 01:07 UTC, AdamSpannbauer approved these changes

2020-10-13 01:07 UTC, merged